### ISSUE TITLE
Have you considered storing player's ID in localstorage?

### ISSUE THREAD

**Issue by ericnewton76** [fanaticscripter/Egg#1]
Cool utilities, but I keep having to retype my player ID into the various utils.  Have you considered saving player id in localstorage and recalling it automatically?

You're using vue, I might submit a PR if you dont mind

**Comment by fanaticscripter** [comment]
ID is already saved to localStorage, independently in each tool. Some people like myself have multiple accounts and use certain tools for certain accounts, some people frequently check other people's accounts with e.g. rockets tracker but don't want to have the ID entered there affect other tools, so it makes sense to keep things separate, and it's not that inconvenient to enter your ID once for each of the ~5 tools that take an ID.

Of course a site-wide ID saving and selection system can be implemented, but that's a lot of work for little benefit.

I guess an easy improvement is to save the last ID used site-wide and recall it when a new tool is used.

**Comment by fanaticscripter** [comment]
> I guess an easy improvement is to save the last ID used site-wide and recall it when a new tool is used.

Implemented.
